### ISSUE TITLE
[UserStory] Identify project stakeholders

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#1]
# User Story
### Essential components
- [x] Title describes the user story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a  _project member_  
I want  _a list of identified stakeholder types_  
so that  _I and others can create appropriate user stories for this project._

## Acceptance Criteria

* Project documentation includes a list of stakeholder types
* Each stakeholder type has a corresponding description of their role in the project
* A minimum of four stakeholder types are identified

## Supporting Information
[Defining Stakeholders](https://conceptainc.com/blog/how-to-define-stakeholders-for-your-software-development-project/) [Concepta 2018]

### Depends On
N/A

**Comment by snoopyvia** [comment]
We have created a sample list of stakeholder as attached. Please move this issue to "in progress". 
[List of Stakeholder.docx](https://github.com/MetroCS/redistricting/files/3752896/List.of.Stakeholder.docx)

**Comment by jody** [comment]
I'm confused.  Where is the list of stakeholders?  Why isn't it somewhere that I can view?
Since this is an "epic", are you sure that you are intending to address the entirety of this user story within a single sprint?

I've changed the status to "in progress" but won't yet make specific assignment until I hear back more about how you are proposing to address this.

**Comment by mykewlker** [comment]
User @snoopyvia will be adding Vision.md document to the repository via pull request. This will include a vision statement and stakeholder list.

**Comment by mykewlker** [comment]
Will three stakeholder types be relevant to complete this issue? If so then this issue can be closed as the vision.md document provides all other acceptance criteria.

**Comment by jody** [comment]
Works for now!
