### ISSUE TITLE
User Story: Readme is clustered needs seperation and structure

### ISSUE THREAD

**Issue by mykewlker** [MetroCS/redistricting#11]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  _Maintainer_
**I want**  _a readme file that states the purpose of the project, stakeholders, and how I can help_
**so that**  _I can be directed to the information I need_

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

- Readme contains a statement that describes the project in terms of what it does
- Readme contains a statement that describes who can use the project and how
- Readme contains a table of contents
- Readme contains links to separate topics
- If readme topics span over 10 screens separate longer topics to additional documents
- Readme contains a Vision statement 
- Readme lists stakeholders
- Readme lists licenses and development language

## Supporting Information
Readme's should be an easily accessible and readable file that quickly identifies the project's intentions, stakeholders, purpose, and development. Topics should be separated and directed to stakeholders and be informative. 

There is a [readme documentation checklist](https://github.com/ddbeck/readme-checklist/blob/master/checklist.md) that offers a template that our readme should follow. This was developed by a technical writer and mimics some industry standards.

**Comment by jody** [comment]
Consider providing different documentation aimed at different stakeholder types (students, instructors, maintainers) rather than a one-size-fits-all documentation scheme.

This may be a good opportunity to require/suggest a separate website entry point.

**Comment by zmorlan1** [comment]
please assign to me as well

**Comment by mykewlker** [comment]
Additional documentation added to this user story. Updated the scenarios, title, and supporting information. Provided additional links to possible checklists that can be used to mitigate changes

**Comment by mykewlker** [comment]
Can this be updated to an EPIC user story

**Comment by jody** [comment]
Why is "student" the appropriate stakeholder for this story?

**Comment by mykewlker** [comment]
Updated stakeholder to "Maintainer" as it better defines the group effected by changes to the readme
