### ISSUE TITLE
[UserStory] Provide graphical rendering of regions and districts

### ISSUE THREAD

**Issue by jody** [MetroCS/redistricting#37]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  {_user, educator}_  
**I want**  _regions and districts to be displayed graphically_  
**so that**  _the meaning and impacts of redistricting and redistricting choices are more apparent_

## Acceptance Criteria
* _Graphical renderings are produced by the product_
* TODO -- Needs concrete acceptance criteria

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
- #33 
- #95

**Comment by jody** [comment]
The ASCII-graphic rendering already in place satisfies this user story.

There is an opportunity to provide a more encompassing Graphical User Interface (GUI) that might make the package more accessible and useful for demonstration and extension. Although that is outside the original scope, it seems like a "good idea" to push further than the example code given in the documentaiton.
